"""Async API for EPO OPS services (MCP-free)."""

from .api import (  # noqa: F401
    BiblioResponse,
    EpoOpsClient,
    FamilyResponse,
    FamilySearchResponse,
    FullTextResponse,
    LegalEventsResponse,
    NumberConversionResponse,
    PdfDownloadResponse,
    SearchResponse,
    convert_number,
    download_pdf,
    fetch_biblio,
    fetch_family,
    fetch_family_details,
    fetch_fulltext,
    fetch_legal_events,
    get_client,
    number_service,
    search_families,
    search_published,
)
from .resources import (  # noqa: F401
    CPC_PARAMETERS_GUIDE,
    CPC_PARAMETERS_RESOURCE_URI,
    CQL_GUIDE,
    CQL_GUIDE_RESOURCE_URI,
    OPS_SWAGGER_RESOURCE_URI,
    get_ops_swagger_spec,
)

__all__ = [
    "EpoOpsClient",
    "SearchResponse",
    "FamilySearchResponse",
    "BiblioResponse",
    "FullTextResponse",
    "FamilyResponse",
    "LegalEventsResponse",
    "PdfDownloadResponse",
    "NumberConversionResponse",
    "get_client",
    "search_published",
    "search_families",
    "fetch_biblio",
    "fetch_fulltext",
    "fetch_family",
    "fetch_family_details",
    "fetch_legal_events",
    "convert_number",
    "number_service",
    "download_pdf",
    "CQL_GUIDE_RESOURCE_URI",
    "CPC_PARAMETERS_RESOURCE_URI",
    "OPS_SWAGGER_RESOURCE_URI",
    "get_ops_swagger_spec",
    "CQL_GUIDE",
    "CPC_PARAMETERS_GUIDE",
]
